# Generated by Django 4.2.3 on 2023-07-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_category_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wachtlist',
            new_name='Watchlist',
        ),
    ]
