# Generated by Django 4.2.3 on 2023-07-10 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_winner_delete_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
