# Generated by Django 4.2.3 on 2023-07-10 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_iscategory_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
